### ISSUE TITLE
Include Cargo.lock in the repository

### ISSUE THREAD

**Issue by abbradar** [Yamakaky/rust-bindgen#248]
This will allow others to make more deterministic builds of the package. My specific use case is building `rust-bindgen` with Nix package manager, which requires all inputs to be pre-determined (i.e. doesn't allow downloading anything without a checksum during the build) -- its Rust infrastructure requires `Cargo.lock` to be present.

**Comment by Yamakaky** [comment]
Since we provide both a bin and a lib, should we do it? Is `Cargo.lock` checked if the crate is used as a dependency?

**Comment by Ralith** [comment]
I just encountered this issue myself. [The documentation](http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) says "Users dependent on the library will not inspect the library’s Cargo.lock (even if it exists)" so it should be safe to include. If it turns out not to be safe, then the binary should be split out into a separate crate so that bindgen can be built reproducibly for distribution.

**Comment by Yamakaky** [comment]
Done.
