### ISSUE TITLE
Add a configuration file

### ISSUE THREAD

**Issue by Yamakaky** [Yamakaky/rust-bindgen#344]
For now it's manageable because there are not a lot of flags, but it could be handy if we allow finer settings, like disabling Debug for a specific type (https://github.com/crabtw/rust-bindgen/issues/342).

**Comment by raphaelcohn** [comment]
In effect, I'm doing this with my [bindgen-wrapper](https://github.com/lemonrock/bindgen-wrapper) tool. It's quite complex, as large C libraries have a lot of niche cases that bindgen can't be expected to reason about. For example, my bindings for DPDK, [dpdk-sys](https://github.com/lemonrock/dpdk-sys).

It'd be great if a lot of what goes in my configuration files could make its way into a bindgen config... For instance, specific overrides for the types of certain hash defines, suppression of warnings / addition of annotations on struct and enums, rename patterns for anonymous structs and unions, correction of bitfield problems, generation of wrappers for macro 'functions' and static inline methods in public APIs, removal of unwanted cruft, etc. Porting C code to work under FFI is hard, and bindgen does a great initial job that is VERY hard, but there's a lot to add to make it part of rinise, repeat workload. It's because a lot of C is just, frankly, crufty.

**Comment by emilio** [comment]
FWIW, in servo we have way more granular configuration due to the complexity introduced by C++, and we handle it with a more complex python script (https://github.com/servo/servo/blob/master/components/style/binding_tools/regen.py). It shouldn't be extremely hard to port a bunch of the non-Gecko-specific bits to a set of configuration files, though it needs a bit of work.
