### ISSUE TITLE
Unsupported type 'Vector'

### ISSUE THREAD

**Issue by JanKaul** [Yamakaky/rust-bindgen#356]
`ERROR:bindgen: unsupported type 'Vector' (/usr/lib/llvm-3.8/bin/../lib/clang/3.8.0/include/mmintrin.h:27:19)`

From

`typedef long long __m64 __attribute__((__vector_size__(8)));`

**Comment by Yamakaky** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html

**Comment by Yamakaky** [comment]
Seems related to SIMD. Not sure what to do, though.

**Comment by Yamakaky** [comment]
For now, I added a better warning.

**Comment by JanKaul** [comment]
Thank you. Apparently SIMD instructions are still experimental in Rust.
[http://www.cs.brandeis.edu/~cs146a/rust/doc-02-21-2015/std/simd/index.html](url)

**Comment by Cobrand** [comment]
`ERROR:bindgen: Vector types are not supported, see https://github.com/crabtw/rust-bindgen/issues/356`, but can we have the line where this error happens as well ? I have several of them in a header file, but I don't know where these error happen exactly.

Also, bindgen stops the whole file when encountering this error, but can we make it only stop for the function that fails to bind ? Maybe print a warning to stderr that the function "x" couldn't have a binding because vectors aren't supported.

Just my 2 cents, I'm trying to create headers for SDL2 and I can't even know what I have to adapt to create such bindings.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
